services:
  db:
    image: kartoza/postgis:15-3.3
    container_name: agora-prod-db
    volumes:
      - agora-prod-db-data:/var/lib/postgresql
      - ./database/dumps:/var/lib/postgresql/dumps
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - FORCE_SSL=FALSE
    restart: on-failure
    networks:
      - agora_network

  api:
    image: agora-api-image:geoserver_proxy # Assuming you've built this image
    container_name: agora-prod-api
    depends_on:
      - db
    command: |
      bash -c '
      cd /src &&
      while !</dev/tcp/db/5432; do sleep 1; done &&
      poetry config virtualenvs.create false &&
      uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src:/src
    environment:
      - WORKING_DIR=/src
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_MINUTES=${REFRESH_TOKEN_EXPIRE_MINUTES}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - ${API_PORT}:8000
    networks:
      - agora_network
  geoserver:
    # build: ./geoserver
    image: agora-geoserver:2.27.6
    container_name: agora-geoserver-prod-container
    environment:
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    volumes:
      - agora-geoserver-data-prod:/geoserver_data/data
    ports:
      - ${GEOSERVER_PORT}:8080
    networks:
      - agora_network

networks:
  agora_network:
    driver: bridge

volumes:
  agora-prod-db-data: 
  agora-geoserver-data-prod:
